"use client";
import type { Metadata } from "next";

import Navbar from "../components/Navbar";

// export const metadata: Metadata = {
//   title: "Coffee Delivery",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
